sudo: false
language: java

before_cache:
  # No sense in caching current build artifacts
  rm -rf $HOME/.m2/repository/com/github/vlsi

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk8
