sudo: false
language: java

before_cache:
  # No sense in caching current build artifacts
  rm -rf $HOME/.m2/repository/com/github/vlsi

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk8

script:
  - mvn package -B -V -P coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
