sudo: false
language: java

before_cache:
  # No sense in caching current build artifacts
  rm -rf $HOME/.m2/repository/com/github/vlsi

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - mvn package -B -V -P coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - "test $TRAVIS_PULL_REQUEST == 'false' && test $TRAVIS_BRANCH == 'master' && test x$SONATYPE_USERNAME != x && mvn deploy -B -V -P release-artifacts --settings settings.xml -DskipTests"
